//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.ChatbotSamples.BotFramework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPath.ChatbotSamples.BotFramework.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there anything else I can help you with?.
        /// </summary>
        public static string Anything_Else {
            get {
                return ResourceManager.GetString("Anything_Else", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can help to search for your order. Can you provide your customer Id?.
        /// </summary>
        public static string Ask_Customer_Id {
            get {
                return ResourceManager.GetString("Ask_Customer_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bye! Have a good day!.
        /// </summary>
        public static string Bye {
            get {
                return ResourceManager.GetString("Bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I was not helpful..
        /// </summary>
        public static string Bye_With_Active_Dialog {
            get {
                return ResourceManager.GetString("Bye_With_Active_Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I don&apos;t have anything to cancel..
        /// </summary>
        public static string Cancel_Fail {
            get {
                return ResourceManager.GetString("Cancel_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have cancelled our last activity..
        /// </summary>
        public static string Cancel_Success {
            get {
                return ResourceManager.GetString("Cancel_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I didn&apos;t understand what you just said to me..
        /// </summary>
        public static string Cannot_Understand {
            get {
                return ResourceManager.GetString("Cannot_Understand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order is not delivered because it is {0}. Do you want me to cancel this one and order from another supplier for you with no extra shipping fee? .
        /// </summary>
        public static string Deliver_Status {
            get {
                return ResourceManager.GetString("Deliver_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can you describe the damage?.
        /// </summary>
        public static string Describe_Damage {
            get {
                return ResourceManager.GetString("Describe_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, how can I help you today?.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can ask me about delayed shipments, broken items, etc..
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, something went wrong. Please retry later..
        /// </summary>
        public static string Internal_Exception {
            get {
                return ResourceManager.GetString("Internal_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t see any other undelivered orders. Would you like to talk to an agent?.
        /// </summary>
        public static string No_Undelivered_Order {
            get {
                return ResourceManager.GetString("No_Undelivered_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of above.
        /// </summary>
        public static string None_Of_Above {
            get {
                return ResourceManager.GetString("None_Of_Above", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order with order number {0} has been cancelled. You can print your return label at {1}. Details have been sent to your email..
        /// </summary>
        public static string Order_Cancelled {
            get {
                return ResourceManager.GetString("Order_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new order has been placed with order number {0}. It is expected to deliver on {1}. Details have been sent to your email..
        /// </summary>
        public static string Order_Created {
            get {
                return ResourceManager.GetString("Order_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve made a note of the damage. Do you want me to return or replace this item?.
        /// </summary>
        public static string Return_Or_Replace {
            get {
                return ResourceManager.GetString("Return_Or_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To talk to a human agent, please call (123)456-7890..
        /// </summary>
        public static string Talk_To_Agent {
            get {
                return ResourceManager.GetString("Talk_To_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you!.
        /// </summary>
        public static string Thank_You {
            get {
                return ResourceManager.GetString("Thank_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I searched for your orders in the past 1 month. Below are the orders that have been delivered to you. Which one are you asking about?.
        /// </summary>
        public static string Which_Delivered {
            get {
                return ResourceManager.GetString("Which_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I searched for your orders in the past 1 month. Below are the orders that have not been delivered yet. Which one are you asking about?.
        /// </summary>
        public static string Which_Undelivered {
            get {
                return ResourceManager.GetString("Which_Undelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working on it....
        /// </summary>
        public static string Working_On {
            get {
                return ResourceManager.GetString("Working_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes .
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
